# Generated by Django 4.2 on 2025-12-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompttemplate',
            name='genre',
            field=models.CharField(max_length=10000, verbose_name='Thể loại video'),
        ),
        migrations.AlterField(
            model_name='videoprofile',
            name='minio_input_path',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='videoprofile',
            name='youtube_link',
            field=models.URLField(max_length=5000),
        ),
    ]
